const Foodapi = [
  {
    id: 1,
    title: "Cheeese Pizza",
    url: "photo/cheese1.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$2",
    fid: "#1",
    category: "cheege pizza",
  },
  {
    id: 2,
    title: "Veggie Pizza",
    url: "photo/vege1.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$3",
    fid: "#2",
    category: "veggie pizza",
  },
  {
    id: 3,
    title: "Meat Pizza",
    url: "photo/meet.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$5",
    fid: "#3",
    category: "meat pizza",
  },

  {
    id: 4,
    title: "BBQ Pizza",
    url: "photo/bbq.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$6",
    fid: "#4",
    category: "bbq pizza",
  },
  {
    id: 5,
    title: "Chicken Pizza",
    url: "photo/chek.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$8",
    fid: "#5",
    category: "chicken pizza",
  },
  {
    id: 6,
    title: "Cheeese Pizza",
    url: "photo/cheese2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$4",
    fid: "#6",
    category: "cheege pizza",
  },
  {
    id: 7,
    title: "Veggie Pizza",
    url: "photo/vege2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$5",
    fid: "#7",
    category: "veggie pizza",
  },
  {
    id: 8,
    title: "BBQ Pizza",
    url: "photo/bbq1.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$1.7",
    fid: "#8",
    category: "bbq pizza",
  },
  {
    id: 9,
    title: "BBQ Pizza",
    url: "photo/bbq2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$3.4",
    fid: "#9",
    category: "bbq pizza",
  },
  {
    id: 10,
    title: "Meat Pizza",
    url: "photo/meet2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$2.1",
    fid: "#10",
    category: "meat pizza",
  },
  {
    id: 11,
    title: "Chicken Pizza",
    url: "photo/chek1.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$5",
    fid: "#11",
    category: "chicken pizza",
  },
  {
    id: 12,
    title: "Veggie Pizza",
    url: "photo/vege3.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$1.1",
    fid: "#12",
    category: "veggie pizza",
  },
  {
    id: 13,
    title: "BBQ Pizza",
    url: "photo/bbq3.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$6.1",
    fid: "#13",
    category: "bbq pizza",
  },
  {
    id: 14,
    title: "Cheeese Pizza",
    url: "photo/cheese4.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$4.3",
    fid: "#14",
    category: "cheege pizza",
  },
  {
    id: 15,
    title: "Chicken Pizza",
    url: "photo/chek2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$3.7",
    fid: "#15",
    category: "chicken pizza",
  },
  {
    id: 16,
    title: "Meat Pizza",
    url: "photo/meet3.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$4",
    fid: "#16",
    category: "meat pizza",
  },
  {
    id: 17,
    title: "Veggie Pizza",
    url: "photo/vege4.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$9",
    fid: "#17",
    category: "veggie pizza",
  },
  {
    id: 18,
    title: "Chicken Pizza",
    url: "photo/chek2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$3.1",
    fid: "#18",
    category: "chicken pizza",
  },
  {
    id: 19,
    title: "Cheeese Pizza",
    url: "photo/vege2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$5.5",
    fid: "#19",
    category: "cheege pizza",
  },
  {
    id: 20,
    title: "Cheeese Pizza",
    url: "photo/chek2.jpg",
    detail: "Yummy pizza is the best.All people love is yummy Pizza",
    price: "$7",
    fid: "#20",
    category: "meat pizza",
  },
];
export default Foodapi;
